name: Build & Deploy UI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service_name:
        required: true
        type: string
      image_route:
        required: true
        type: string
    secrets:
      IP_DEV:
        required: true
      IP_PROD:
        required: true
      PRIVATE_KEY_DEV:
        required: true
      PRIVATE_KEY_PROD:
        required: true
      SSH_USER:
        required: true
      GHCR_USER:
        required: true
      GHCR_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | \
            docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

      - name: Build UI Docker image
        run: docker build -t ${{ inputs.image_route }} .

      - name: Push UI Docker image
        run: docker push ${{ inputs.image_route }}

  deployment:
    name: Deploy UI to VM
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Add SSH key (production)
        if: ${{ inputs.environment == 'production' }}
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_PROD }}

      - name: Add SSH key (development)
        if: ${{ inputs.environment != 'production' }}
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_DEV }}

      - name: Deploy UI
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            TARGET_IP="${{ secrets.IP_PROD }}"
            COMPOSE_FILE="docker-compose.prod.yml"
          else
            TARGET_IP="${{ secrets.IP_DEV }}"
            COMPOSE_FILE="docker-compose.dev.yml"
          fi

          echo "Deploying to $TARGET_IP using $COMPOSE_FILE"

          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@$TARGET_IP <<EOF
              set -e
              cd infra-ingsis
              echo "${{ secrets.GHCR_TOKEN }}" | \
                docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
              docker pull ${{ inputs.image_route }}
              docker compose -f ${COMPOSE_FILE} up -d ${{ inputs.service_name }}
          EOF
